language: node_js
node_js: 8

matrix:
  include:
    - language: android
      os: linux
      jdk: oraclejdk8
      env:
        - REACT_NATIVE_VERSION=0.51.1
      android:
        components:
          - build-tools-27.0.3
          - build-tools-27.0.2
          - build-tools-26.0.2
          - android-24
          - android-25
          - android-26
          - android-27
          - android-28
          - extra-android-m2repository
          - extra-google-google_play_services
          - extra-google-m2repository
          - sys-img-armeabi-v7a-android-24
          - sys-img-armeabi-v7a-android-25
          - sys-img-armeabi-v7a-android-26
          - sys-img-armeabi-v7a-android-27
          - sys-img-armeabi-v7a-android-28
      install:
        - npm install -g react-native-cli >/dev/null 2>&1
        - npm install -g detox-cli >/dev/null 2>&1
        - gem install xcpretty >/dev/null 2>&1
        - gem install github_changelog_generator
        - android list targets
        - android create avd --force -n Pixel_2_API_28 -t android-24 --abi armeabi-v7a
      script:
        - pwd
        - npm install
        - npm start &
        - detox build --configuration android.emu.debug
        - detox test  --configuration android.emu.debug --headless --no-color

branches:
  only:
  - master
before_install:
  - nvm install 8
  - pip install awscli --upgrade --user
notifications:
  email: true