language: node_js
node_js: 8

matrix:
  include:
    - language: android
      os: linux
      jdk: oraclejdk8
      env:
        - REACT_NATIVE_VERSION=0.51.1
      android:
        components:
          - build-tools;27.0.3
          - build-tools-27.0.2
          - build-tools-26.0.2
          - android-27
          - extra-android-m2repository
          - extra-google-google_play_services
          - extra-google-m2repository
          - sys-img-armeabi-v7a-android-27
      install:
      - npm install -g react-native-cli >/dev/null 2>&1
      - npm install -g detox-cli >/dev/null 2>&1
      - gem install xcpretty >/dev/null 2>&1
      - gem install github_changelog_generator
      script:
      - pwd
      - npm install
      - npm start &
      - detox build --configuration android.emu.debug
      - detox test  --configuration android.emu.debug --headless --no-color

branches:
  only:
  - master
before_install:
  - nvm install 8
  - pip install awscli --upgrade --user
notifications:
  email: true