language: node_js
node_js: 8

matrix:
  include:
    - language: android
      os: linux
      jdk: oraclejdk8
      env:
        - REACT_NATIVE_VERSION=0.51.1
        global:
          - ANDROID_API_LEVEL=27
          - ANDROID_BUILD_TOOLS_VERSION=27.0.2
      android:
        components:
          - tools
          - platform-tools
          - tools
          - build-tools-$ANDROID_BUILD_TOOLS_VERSION
          - android-$ANDROID_API_LEVEL
          - extra-android-m2repository
          - extra-google-google_play_services
          - extra-google-m2repository
          - sys-img-armeabi-v7a-android-$ANDROID_API_LEVEL
          - sys-img-armeabi-v7a-google_apis-$ANDROID_API_LEVEL
          - sys-img-x86_64-android-$ANDROID_API_LEVEL
          - sys-img-x86-android-$ANDROID_API_LEVEL
      install:
        - npm install -g react-native-cli >/dev/null 2>&1
        - npm install -g detox-cli >/dev/null 2>&1
        - gem install xcpretty >/dev/null 2>&1
        - gem install github_changelog_generator
        - android list targets
        - echo no | android create avd --force -n Pixel_2_API_28 -t android-$ANDROID_API_LEVEL --abi google_apis/armeabi-v7a
        - emulator -avd test -no-audio -no-window &
        - android-wait-for-emulator
        - adb shell input keyevent 82 &
      script:
        - npm install
        - npm start &
        - detox build --configuration android.emu.debug
        - detox test  --configuration android.emu.debug --headless --no-color

branches:
  only:
  - master
before_install:
  - nvm install 8
  - pip install awscli --upgrade --user
notifications:
  email: true